### ISSUE TITLE
Error with image shape

### ISSUE THREAD

**Issue by mzur** [biigle/magic-sam#18]
So there was this error:

```
    Error while executing python command '/var/www/vendor/biigle/magic-sam/src/config/../resources/scripts/compute_embedding.py '/var/www/storage/magic_sam/sam_chec ▶
    /var/www/vendor/biigle/magic-sam/src/config/../resources/scripts/compute_embedding.py:35: DeprecationWarning: An exception was ignored while fetching the attrib ▶
      input_image = transform.apply_image(np.array(image))
    Traceback (most recent call last):
      File "/var/www/vendor/biigle/magic-sam/src/config/../resources/scripts/compute_embedding.py", line 35, in <module>
        input_image = transform.apply_image(np.array(image))
      File "/opt/conda/lib/python3.10/site-packages/segment_anything/utils/transforms.py", line 30, in apply_image
        target_size = self.get_preprocess_shape(image.shape[0], image.shape[1], self.target_length)
    IndexError: tuple index out of range
```

I remember errors like this one in other scenarios with grayscale images (that have one dimension less) but I though we were already [taking care of that](https://github.com/biigle/magic-sam/blob/8db9066e7cd2eeeccae260407fca0e4339234a41/src/resources/scripts/compute_embedding.py#L24-L32) in the script. Is there an image mode that we didn't consider, yet? @dlangenk do you have any idea what's going on?

**Comment by dlangenk** [comment]
I ran the script on my machine and it works without any problems. It's also a regular RGB image. I found another error in the script though but this is only happening for int32 images. I'll fix it later. We're talking about image 2140218 don't we?

**Comment by mzur** [comment]
> We're talking about image 2140218 don't we?

Yes. If it works for you then maybe there was an issue with the image cache and the image file was corrupt. I resubmitted the failed job and it seems to have worked now. Thanks for checking.
