### ISSUE TITLE
API endpoint to upload embedding

### ISSUE THREAD

**Issue by dlangenk** [biigle/magic-sam#24]
I have a script that computes the embeddings and uploads them to Biigle. Currently I use s3 to upload them. However, this is only possible by me because I have direct access rights to s3. An api endpoint that allows the upload of embeddings would make it possible to publish the script as community script. But I guess there might be security concerns (uploading of data) and if #5 is implemented this would be more or less obsolete.

**Comment by mzur** [comment]
I would definitely prefer #5 over this. We can't trust unvalidated user uploads like that and I don't know how we could easily validate it, as it is just a binary blob.
