### ISSUE TITLE
(0,0) negative point

### ISSUE THREAD

**Issue by dlangenk** [biigle/magic-sam#28]
Is there a reason for the negative point at (0,0). It works quite well without it, and it could in very rare cases lead to false results if (0,0) is important ;-)

**Comment by mzur** [comment]
The code in question is this: https://github.com/biigle/magic-sam/blob/107c74696b70de949ea189dc066c87541062f7f2/src/resources/assets/js/ol/MagicSamInteraction.js#L145-L148

We have to check the example on which Daniel built the initial MagicSAM demonstrator and find out why the code looks like that. Maybe the (0, 0) point can be deleted.

**Comment by dlangenk** [comment]
For some reason not really explained the second (0,0) point is also set in the reference implementation ([facebook demo](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/demo/src/components/helpers/onnxModelAPI.tsx#L34) and [notebook onnx example](https://github.com/facebookresearch/segment-anything/blob/main/notebooks/onnx_model_example.ipynb). I guess since point coords encodes for both single point as well as boxes this is just the encoding for a single point to distinguish it from a box.
