### ISSUE TITLE
Bulk-create embeddings

### ISSUE THREAD

**Issue by dlangenk** [biigle/magic-sam#5]
Explore the possibility to use an inference server to speed up the generation of SAM embeddings, because currently most of the time is spend loading the weights, modules, etc.

**Comment by mzur** [comment]
My 2ct: A solution where a whole volume is simply processed and embeddings are generated for each image would better fit to the current architecture and deployment of BIIGLE. This could also be treated as a "long-running GPU job" like MAIA jobs and we won't need separate a "fast" GPU worker any more. The embeddings can be stored for as long as the images exist in BIIGLE.

How could the UI for this look like? Users could press a button for the volume (like laser pont detection) and get a notification once the volume is fully processed. Then they can use Magic SAM without long waiting times. If an image or the volume is deleted, the embeddings are deleted as well.

**Comment by dlangenk** [comment]
Yeah I guess you're right. But if possible it might be nice to process them in the Biigle upload order so you can start with the annotation as soon as the job starts and the first embeddings are generated. Having a progress indicator (using websockets?) might also be a nice to have.

**Comment by mzur** [comment]
A progress indicator should be possible. It shouldn't take more than a few minutes to process a regular volume (if a worker is available).

I'm hesitant to "preemptively" process all images. This might waste a lot of storage capacity after all (if SAM isn't used).

**Comment by dlangenk** [comment]
> A progress indicator should be possible. It shouldn't take more than a few minutes to process a regular volume (if a worker is available).
> 
> I'm hesitant to "preemptively" process all images. This might waste a lot of storage capacity after all (if SAM isn't used).

That was formulated a bit misleadingly by me. Biigle upload order -> In the order of the Biigle ids. I do not want to do this on upload.

**Comment by mzur** [comment]
I thought about it a little more and I now like this idea: Almost nothing changes from the status quo. A user visits an image, presses the button and then has to wait a few seconds on the embedding (if it doesn't exist yet). But now the button press also triggers a second ("slow") queue job. The second job computes the embeddings for all the remaining images in the volume (starting with the next image the user will visit). When the user switches to the next image and presses the button, the embedding should be already there. The embeddings can be kept for a long time (~6 months?). After that the process starts from the beginning.

The only downside is that we will have to keep two separate fast/slow GPU workers. If the slow GPU queue is currently full, it's bad luck for the user but I think this won't happen most of the time. But the UI won't have to change.

**Comment by dlangenk** [comment]
Sounds good to me. But what if the user requests embeddings for a certain image which is already queued in the slow queue. Will we still process that in the fast queue and then skip the image in the slow queue if the embedding already exists (we could just check if it exists in the python script before computing)?

**Comment by mzur** [comment]
If the slow job is still waiting, it can skip the image once it runs. If the Python script is already running I'd say it can just compute the embedding again.

**Comment by mzur** [comment]
@dlangenk This is assigned to you. Are you working on this? Otherwise I might pick this up sometime.

**Comment by dlangenk** [comment]
Not currently but this is rather easy to do. Do you just want a python script that iterates over the images?

**Comment by mzur** [comment]
> Do you just want a python script that iterates over the images?

That's the easy part :wink: The [script](https://github.com/biigle/magic-sam/blob/main/src/resources/scripts/compute_embedding.py) has to be updated to accept multiple images as input. This only scales well if it reads a file with image paths and returns a file with embedding paths. If you want, you can implement this in a new branch. I'll pick it up and implement the PHP stuff. Then I'll also implement a new queue job and the logic to bulk-create embeddings for a whole volume.

**Comment by dlangenk** [comment]
I added a new branch with the updated script. Input and output files are json files with e.g. input.json: ["12345.jpg","6789.jpg"], output.json: ["12345.npy","6789.npy"]. Batching was slightly slower then serial processing.

**Comment by dlangenk** [comment]
If the volume is rather large the job will run for some time and I don't know if we can contact the websocket in between that the current image is already processed. Otherwise the user might be forced to wait for quite some time. If we cannot contact the websocket we could also split this into two (or n) seperate jobs.

**Comment by mzur** [comment]
Thanks for the script! I don't plan to use websockets for the long job. If the embedding file was not uploaded yet, another job to compute just this file will be dispatched, just as it is now.

If we want to do something fancy, we could also try a streaming approach, where the Python script returns a filename line by line which is then read by PHP. Each new (completed) file can be uploaded while the Python script is still running. But this is probably complicated to implement on the PHP side.

**Comment by dlangenk** [comment]
What I mean is the following: You are currently at image 116 (id is random). If you now click the wizard hat, the long job ist started. Now you are waiting for say 5 minute in image 116. You don't get any response from the backend, but your weights for 116 are already there you just don't know without reloading. Or do you dispatch two jobs? One short running for the current image 116 and a long one for the rest 117-599? In that case we have to keep track if you go to 200 after 116 and the weight is not there you will submit another two jobs.

**Comment by mzur** [comment]
I planned to submit two jobs. Since we only have one "fast" GPU and one "slow" GPU, the jobs are processed one after the other on each queue. When the second slow job is processed, it notices that all embeddings are already there and does nothing.

**Comment by dlangenk** [comment]
Sure if they are already there. But what if they are not there at that point in time? Then it looks like they have never been requested (if I get that right).

**Comment by mzur** [comment]
They will be there because the slow job to create them all was already finished. The frontend may not see the embeddings yet and will submit the jobs twice but the user will get the embedding as fast as possible and nothing will be actually computed twice.

**Comment by dlangenk** [comment]
Close this issue for now as the permanent python gpu worker (#29) will make this obsolete.
