### ISSUE TITLE
Ignore EXIF rotation to compute embeddings

### ISSUE THREAD

**Issue by dlangenk** [biigle/magic-sam#7]
Some images might have a rotation flag set and it is neglected in some libraries but not in all, which leads to different orientations of the images used. E.g. in https://biigle.de/images/2240959/annotations

**Comment by mzur** [comment]
The image is read with Pillow which automatically rotates it:

https://github.com/biigle/magic-sam/blob/09ab1cb13edbb2e21175632365d480ac9861b4fc/src/resources/scripts/compute_embedding.py#L22

You can ignore the EXIF rotation by using Vips ([as MAIA did in v1](https://github.com/biigle/maia/blob/v1.24.0/src/resources/scripts/instance-segmentation/Dataset.py#L29-L30) and probably also should in v2). We should use Vips here, too.

**Comment by lehecht** [comment]
Can this issue be closed now?

**Comment by dlangenk** [comment]
I guess there is still something off with the display of the images (and likely also with SAM). If you have a look at the example I posted above (https://biigle.de/images/2240959/annotations) and then at the original file (https://biigle.de/api/v1/images/2240959/file) part of the image is missing. Regarding this issue, it depends what the correct display of the image is. But the display of the image does not fit to the SAM results at least.

**Comment by lehecht** [comment]
> I guess there is still something off with the display of the images (and likely also with SAM). If you have a look at the example I posted above (https://biigle.de/images/2240959/annotations) and then at the original file (https://biigle.de/api/v1/images/2240959/file) part of the image is missing. Regarding this issue, it depends what the correct display of the image is. But the display of the image does not fit to the SAM results at least.

Unfortunately, I am not authorized to see your example.

**Comment by mzur** [comment]
@dlangenk I see the full image. I had a similar report of a user a few days ago. Maybe the de.NBI S3 has some trouble?

@lehecht No this issue can't be closed yet. It's no about the display in the annotation tool but about the image orientation used when the SAM embedding is created. If the image is not rotated in the annotation tool but it is rotated when the embedding is computed, the embedding does not fit to the displayed image. We need to update the SAM code so it also ignores the image orientation.

**Comment by dlangenk** [comment]
Ah sorry. I added you so that you can have a look.

**Comment by mzur** [comment]
Ok the image is displayed incorrectly in Chrome... what a pain with this stupid auto-rotation...

**Comment by mzur** [comment]
The display bug is still unrelated to this issue, though. Here is my PR when I last tried to fix the display rotation: https://github.com/biigle/core/pull/809

**Comment by dlangenk** [comment]
> Ok the image is displayed incorrectly in Chrome... what a pain with this stupid auto-rotation...

I can confirm that. With Firefox it works with Chrome not .... but the orientation is the same with Chrome and Firefox. Looks more like an extent (or something similar) issue with Openlayers probably? I guess the image orientation is correct (landscape mode) but the display area still has the wrong orientation (portrait).

**Comment by mzur** [comment]
I see a different rotation, too.

Firefox: 
![Screenshot from 2024-05-17 09-50-28](https://github.com/biigle/magic-sam/assets/2457311/850fabd9-1d6f-4472-a5ff-942ad01c87dd)

Chrome:
![Screenshot from 2024-05-17 09-50-33](https://github.com/biigle/magic-sam/assets/2457311/efa34d9b-c45d-4773-baec-c29e1bd38ac1)


Let's move any additional discussion to https://github.com/biigle/core/issues/833, as it's unrelated to this issue.

**Comment by lehecht** [comment]
Is this issue still open?

**Comment by mzur** [comment]
Yes

**Comment by mzur** [comment]
We could not reproduce the issue. Everything works as expected with a EXIF-rotated image.
